services:
  apache:
    build: .
    ports:
      - '8080:80'
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./cgi-bin:/usr/local/apache2/cgi-bin
